### ISSUE TITLE
caffeNetViewer Çalıştırılması

### ISSUE THREAD

**Issue by apassenger** [birolkuyumcu/caffeNetViewer#1]
Merhaba;
Python da yeniyim yani sizinle ilerliyorum
Çalıştırırmak için  tam olarak ne yapmalıyım ?
pyside ve opencv kurulu caffe yi kurdum caffeNetViewer çalışmayınca sizin derlenmiş olarak sunduğunuz caffeyi indirdim Dolayısı ile pycaffe de elimde Fakat uygulamayı açamıyorum

**Comment by birolkuyumcu** [comment]
hata nedir ?

**Comment by apassenger** [comment]
Merhaba;
caffenetviewer_ui.py ve caffenetviewer_ui.pyc yi python27/Lib klosörü altına ekledim ve sonra python idle da import ettim 
Hata yok ama program açılmadı (import etti ama program açılmadı )Ekran görüntüsü aşağıdadır 
[https://i.resimyukle.xyz/cG87B.png](url)

**Comment by birolkuyumcu** [comment]
bir şey import etmeyeceksiniz caffeNetViewer.py python kodunu çalıştıracaksınız
python bilginizi pekiştirin
